### ISSUE TITLE
Only fill second dropdown with possible shapes in algorithm shape visualizer

### ISSUE THREAD

**Issue by bugybunny** [sp3ctum/squanmate#19]
I’m not sure if it is necessary to create an image for, lets say 8/8 or star/star that is not possible with a Square-1. Should be easy to implement, just count the number of edges and corners in the first selected dropdown and then filter in the second. 

But might be a UI nightmare :D Maybe you could disable the second dropdown until the first is filled and also add a switch button to the right to switch top with bottom and vice versa.

**Comment by sp3ctum** [comment]
Ah, you're right. This is a very good idea.
Also I like the idea of the "switch layers" button.

**Comment by sp3ctum** [comment]
I implemented the "switch layers" button. Maybe it can help with seeing how the algorithms are mirrored.

**Comment by sp3ctum** [comment]
The filtering of the second layer based on the first layer is now done as well (v. 3.5). Thanks for the idea!
