### ISSUE TITLE
Switch top and bottom color with left/right color switch

### ISSUE THREAD

**Issue by a791705799** [sp3ctum/squanmate#28]
Or the cube color scheme would be weird.

**Comment by sp3ctum** [comment]
There is no left/right color switch. Maybe you mean the `Use back face as front face (rotate Y2)` option?

Its purpose is just to do a Y2 move. You can switch the top and bottom colors with another option.

**Comment by a791705799** [comment]
Nope. If I choose the top/bottom switch, the color scheme would be like this: Yellow top, white bottom, orange front, red back, blue left, green right. While it supposed to be blue right and green left if you were using a normal color scheme.
What I mean is to switch top/bottom and left/right at the same time, that would make it a normal squan rather than a weird color scheme squan.

**Comment by sp3ctum** [comment]
Ah I see what you mean.. I hope. z2 is not supported by the color chooser. It may be a bit confusing. Here's what it's supposed to help with:

- as a solver, I have yellow on top instead of white, and I want to see this reflected in the preview. I click on "swap top and bottom colors"
- as a solver, I like to solve with red in the front instead of the default (orange). I click on "rotate y2".

**Comment by sp3ctum** [comment]
What is the use case of a z2 flip like you described? Maybe some kind of left handed thing?

**Comment by a791705799** [comment]
NO......Let me explain this again, only switch yellow and white won't make it a correct squan.
Is it clear?

**Comment by sp3ctum** [comment]
Oh, the use case for having yellow on top is that that is the default color scheme for the Xman Volt, while the white on top is the default for the QiYi Square One

**Comment by a791705799** [comment]
And for this, qiyi squan is also yellow on top as default.

**Comment by sp3ctum** [comment]
Well, mine is.. they must make different versions then.

What colors do you have on each side of your squan?

**Comment by a791705799** [comment]
For my qiyi/volt, yellow top, white bottom, orange front, red back, green left, blue right.
And if you switch the two long caps in the middle layer(mainly the green one with the logo and the blue one without the logo), and do /6,6/.Then it would be the same as yours.

**Comment by sp3ctum** [comment]
Oh I see now! I forgot I switched the caps on my Volt. This seems like a bug, I'll look into it..

Sorry for being so dense 😁

**Comment by a791705799** [comment]
Bingliang Li said he need custom color scheme. His scheme was orange top and black bottom, which squanmate didn't contain.

**Comment by sp3ctum** [comment]
Please open another issue for that, it can contain the same text.

**Comment by sp3ctum** [comment]
Fixed in https://github.com/sp3ctum/squanmate/commit/4190aed , not released yet

**Comment by sp3ctum** [comment]
Left this open by accident. Closing.
