### ISSUE TITLE
Make "General", "Parity" and "Colors" frames completely clickable to expand in Scramble Inspector

### ISSUE THREAD

**Issue by bugybunny** [sp3ctum/squanmate#35]
![image](https://user-images.githubusercontent.com/5311105/34135801-11656cf0-e463-11e7-9b89-9432255a911c.png)

The whole red area should also be clickable, not only the text. Expanding the box is tedious, especially if you have to do it a lot.

An option to always have the parity box open for example would also be nice. An option have all boxes open always would be sufficient, at least for web. I guess for mobile it would take too much space and require scrolling.

**Comment by bugybunny** [comment]
Ok, I just noticed it is everywhere. I hope this is easy fixable, I guess you’re using a framework for that :D

**Comment by sp3ctum** [comment]
Hi, these are great ideas I think! Thanks for opening this.

They don't seem too hard to fix. However, I've unfortunately had some hand pain recently, and have been trying to recover from it. Haven't been able to solve my puzzles at all. I'm a bit worried about it as I have to type on my keyboard to make a living, and I've tried to keep it to a minimum recently :(

I'll see how much the upcoming holidays will heal my hands. Maybe if I am feeling better I can work on your suggestions.

**Comment by sp3ctum** [comment]
I made the panel headers clickable at their entire length now. It's still not perfect but noticeably better.
