### ISSUE TITLE
Parity scrambler should check if end result is sliceable

### ISSUE THREAD

**Issue by bugybunny** [sp3ctum/squanmate#38]
I got a 8/star scramble ending with `… / (1,4)` which is not a legal position and you cannot get in an official scramble. I tracked it down in the code but have never worked with Closure (otherwise I would have tried to fix it myself) and I believe the problem is in [default_scrambler.cljs#L24](https://github.com/sp3ctum/squanmate/blob/2d3eeb9967a50de69ec7dfea75c775b377dadc62/src/squanmate/scramblers/shape_scrambler/default_scrambler.cljs#L24) that is used by `new-default-shape-scrambler` without checking after if the state is sliceable.

**Comment by sp3ctum** [comment]
This is actually a feature - the scrambler adds random rotations. But you are correct, it does not guarantee that the starting position is sliceable.

Are you sure that it is not a legal position? I remember researching this in the summer when I made the scrambler, and found nothing regarding that.

That being said, if it really is the case that only sliceable starting positions are given by the official scramble, I feel this should be in line with that. It doesn't add that much value, and people are just going to be confused by this behavior in that case.

**Comment by bugybunny** [comment]
Hmm, interesting. I thought that would be written somewhere (e.g. in the regulations) but it is not. I guess it could be found in tnoodle https://github.com/thewca/tnoodle/blob/1907465e421362d69b7bc2b3e0acb22437d7cee6/sq12phase/src/cs/sq12phase/FullCube.java#L42 when the random state is selected. Random state already seems to include the moves after the last slash, they do not add any moves after applying the random state scramble https://github.com/thewca/tnoodle/blob/1907465e421362d69b7bc2b3e0acb22437d7cee6/scrambles/src/puzzle/SquareOnePuzzle.java#L39. But my brain could not parse all this `randomCube` stuff and they use a python based make program which makes debugging impossible (? not sure). 

So I asked my delegate and he said that they always have to end in a sliceable position.

**Comment by sp3ctum** [comment]
I made all scrambles start at a random sliceable position now. It's available in version 5.9.1

See if it works for you.
