### ISSUE TITLE
"Choose none" only works if all shapes are activated

### ISSUE THREAD

**Issue by bugybunny** [sp3ctum/squanmate#40]
![image](https://user-images.githubusercontent.com/5311105/34538308-3728ee1a-f0cc-11e7-9f9a-031c0c80551b.png)

`Select none` only does something if not all shapes are activated.

**Comment by sp3ctum** [comment]
Oh, you're right. Thanks for reporting.

I'll fix it in a couple of days I think.

**Comment by sp3ctum** [comment]
I was able to fix this is version 6.0 via https://github.com/sp3ctum/squanmate/commit/02f82f4
