### ISSUE TITLE
Rarely, the scrambler spits out an illegal scramble with a missing /

### ISSUE THREAD

**Issue by bugybunny** [sp3ctum/squanmate#47]
Just got this with 6.4 when training CSP
![image](https://user-images.githubusercontent.com/5311105/35057316-dcdec788-fbb4-11e7-866c-84a414c1fd40.png)

/ is missing and it also becomes unsliceable. Never had this before and also no idea how to reproduce this. I had 6/90 shapes selected (the first 6 Square shapes from your Google Sheet) and generated a new scramble by pressing `New scramble`

**Comment by sp3ctum** [comment]
Wow this is interesting...

I actually could reproduce it! It occurred with the square square case.

**Comment by sp3ctum** [comment]
It used to display a part of the algorithm's beginning, then some from the end, then again some from the start etc. So the ordering was not defined for all cases.

This is now fixed with version 6.5.

**Comment by bugybunny** [comment]
Interesting. And thanks for the quick bug fixes always :)
