### ISSUE TITLE
Scramble Inspector does not work anymore with 6.7

### ISSUE THREAD

**Issue by bugybunny** [sp3ctum/squanmate#48]
I get this in the console when I try to inspect a scramble either from the cubeshape trainer with `Inspect` or by entering my own scramble.

squanmate.js:3924 Error rendering component (in nu > page > pK > pK > nK > kK > iK > EJ)
(anonymous) @ squanmate.js:3924
squanmate.js:3453 Uncaught Error: No protocol method IDeref.-deref defined for type string: (4,5)/
    at x (squanmate.js:3440)
    at B (squanmate.js:3453)
    at Object.EJ [as reagentRender] (squanmate.js:4445)
    at squanmate.js:3922
    at rt (squanmate.js:3923)
    at squanmate.js:3924
    at Ks (squanmate.js:3900)
    at Ls (squanmate.js:3901)
    at it (squanmate.js:3921)
    at Object.render (squanmate.js:3924)
2squanmate.js:4013 ERROR: Cannot create sketch. :host is not specified.

**Comment by sp3ctum** [comment]
Oops, this is my bad. Already made a fix, hold on. I'll release it asap.

**Comment by sp3ctum** [comment]
Okay, fixed this in https://github.com/sp3ctum/squanmate/commit/a7d5011

There is now a 6.7.1 release where the inspector works.

Thanks man!

**Comment by bugybunny** [comment]
I always use the /master/resources/public/ because I don’t see the reason to always have to switch the version number in the URL. It’s the same, right? 

If so, is there a reason why you always put the link with the exact version number into the readme instead of just once the one that I use.

**Comment by sp3ctum** [comment]
Originally I did that... But then I discovered there are some rare issues
with not loading the latest JavaScript, but instead using an older one.

I've out some research into this, and I might I want to make switch to a
link like that. I still want to see how saved data will be handled with
that kind of link.
