### ISSUE TITLE
PLL Algorithm Trainer sometimes generates non-PLL cases

### ISSUE THREAD

**Issue by Wo0fle** [sp3ctum/squanmate#60]
Sometimes (not often but not exactly rarely either), generating a PLL case in the algorithm trainer creates a non-PLL case such as this one:

![da wrong case](https://user-images.githubusercontent.com/81187812/200188261-28144547-9cbe-4e9e-a427-26e60b8d8c7f.png)

It is not always exactly this but I'm fairly sure it is always an M2 case.

I have only used the even-parity PLL trainer so I'm not sure if this happens anywhere else.

**Comment by mikavilpas** [comment]
Hi, sorry about the bug. I haven't touched the puzzle in years myself and I think this project needs a new maintainer.. I have forgotten most of the terms and can't solve the puzzle anymore.

**Comment by Wo0fle** [comment]
Oh ok, I'm sorry for necroposting!
